# frozen_string_literal: true

require_relative "api/clients/base"
require_relative "api/clients/all"

require_relative "api/clients/actions"
require_relative "api/clients/donations"
require_relative "api/clients/newsletter_subscriptions"
require_relative "api/clients/projects"
require_relative "api/clients/segments"
require_relative "api/clients/sites"
require_relative "api/clients/teams"
require_relative "api/clients/users"

require_relative "api/resources/base"
require_relative "api/resources/list"
require_relative "api/resources/resource"

require_relative "api/resources/action"
require_relative "api/resources/actions"
require_relative "api/resources/activity"
require_relative "api/resources/address"
require_relative "api/resources/banner"
require_relative "api/resources/consent"
require_relative "api/resources/donation"
require_relative "api/resources/donations"
require_relative "api/resources/location"
require_relative "api/resources/newsletter_subscription"
require_relative "api/resources/newsletter_subscriptions"
require_relative "api/resources/photo"
require_relative "api/resources/project"
require_relative "api/resources/projects"
require_relative "api/resources/question"
require_relative "api/resources/registration_fee"
require_relative "api/resources/reward"
require_relative "api/resources/segment"
require_relative "api/resources/segments"
require_relative "api/resources/site"
require_relative "api/resources/team"
require_relative "api/resources/teams"
require_relative "api/resources/user"
require_relative "api/resources/users"
require_relative "api/resources/video"

require_relative "api/client"
require_relative "api/config"
require_relative "api/exception"
require_relative "api/finder"
require_relative "api/request"
require_relative "api/response"

require_relative "api/version"
