# frozen_string_literal: true

require_relative "api/requests/base"
require_relative "api/requests/all"

require_relative "api/requests/actions"
require_relative "api/requests/donations"
require_relative "api/requests/newsletter_subscriptions"
require_relative "api/requests/projects"
require_relative "api/requests/segments"
require_relative "api/requests/sites"
require_relative "api/requests/teams"

require_relative "api/responses/base"
require_relative "api/responses/pagination"
require_relative "api/responses/resource"

require_relative "api/responses/action"
require_relative "api/responses/actions"
require_relative "api/responses/address"
require_relative "api/responses/banner"
require_relative "api/responses/donation"
require_relative "api/responses/donations"
require_relative "api/responses/newsletter_subscription"
require_relative "api/responses/newsletter_subscriptions"
require_relative "api/responses/owner"
require_relative "api/responses/photo"
require_relative "api/responses/project"
require_relative "api/responses/projects"
require_relative "api/responses/question"
require_relative "api/responses/reward"
require_relative "api/responses/segment"
require_relative "api/responses/segments"
require_relative "api/responses/site"
require_relative "api/responses/team"
require_relative "api/responses/teams"
require_relative "api/responses/video"

require_relative "api/client"
require_relative "api/http"

require_relative "api/version"
