# frozen_string_literal: true

require_relative 'api/resources/base'
require_relative 'api/resources/error'
require_relative 'api/resources/list'
require_relative 'api/resources/resource'

require_relative 'api/resources/action'
require_relative 'api/resources/activity'
require_relative 'api/resources/address'
require_relative 'api/resources/banner'
require_relative 'api/resources/consent'
require_relative 'api/resources/contact'
require_relative 'api/resources/donation_form'
require_relative 'api/resources/donation'
require_relative 'api/resources/location'
require_relative 'api/resources/manual_donation'
require_relative 'api/resources/newsletter_subscription'
require_relative 'api/resources/performance'
require_relative 'api/resources/performance_photo'
require_relative 'api/resources/photo'
require_relative 'api/resources/project'
require_relative 'api/resources/recurring_donor'
require_relative 'api/resources/registration_fee'
require_relative 'api/resources/reward'
require_relative 'api/resources/question'
require_relative 'api/resources/segment'
require_relative 'api/resources/site'
require_relative 'api/resources/sites'
require_relative 'api/resources/team'
require_relative 'api/resources/user'
require_relative 'api/resources/users'
require_relative 'api/resources/video'

require_relative 'api/client'
require_relative 'api/config'
require_relative 'api/deprecation'
require_relative 'api/exception'
require_relative 'api/request'
require_relative 'api/response'
require_relative 'api/util'

require_relative 'api/version'
